# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opc < Formula
  desc "CLI companion for platform engineers — persistent context, memory, and session management for agent-assisted workflows"
  homepage "https://github.com/opscompanion/opc"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opscompanion/opc/releases/download/v0.2.0/opc_darwin_amd64.tar.gz"
      sha256 "6ebb07ef34652ab668b89e5ade3d383663e753f0eef992042370456e359aa810"

      define_method(:install) do
        bin.install "opc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opscompanion/opc/releases/download/v0.2.0/opc_darwin_arm64.tar.gz"
      sha256 "0432030b921bd19eeadaa6e0db2fa81ebf40b2a1d0ea7b18dfa51b2107e9b413"

      define_method(:install) do
        bin.install "opc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/opscompanion/opc/releases/download/v0.2.0/opc_linux_amd64.tar.gz"
      sha256 "0fe088c9e55b6cd98f6f72b6442175e6c03a65c84462fcd0383d3f744749a5c8"
      define_method(:install) do
        bin.install "opc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opscompanion/opc/releases/download/v0.2.0/opc_linux_arm64.tar.gz"
      sha256 "3fa5953a548964a96cfebe2b7e67312bb7a321280eceac7e556e1f042c769bae"
      define_method(:install) do
        bin.install "opc"
      end
    end
  end

  test do
    system "#{bin}/opc", "version"
  end
end
